TwoTicketsPizza/urls.py
from django.contrib import admin
from django.urls import path
from shop.views import home_view, order_view, order_list_view, success_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view),
    path('order/<str:pizza_type>/<str:pizza_size>/', order_view),
    path('orders/', order_list_view),
    path('success/', success_view),
]

shop/models.py
from django.db import models


class Order(models.Model):
    pizza_sizes = [
        ("S", "Small"),
        ("M", "Medium"),
        ("L", "Large"),
    ]

    pizza_type = models.CharField(max_length=30)
    pizza_size = models.CharField(max_length=1, choices=pizza_sizes, default="M")
    client_name = models.CharField(max_length=70)
    client_email = models.CharField(max_length=255)  # RFC 3696 Email max length
    client_phone = models.CharField(max_length=15)  # ITU max Length for phone numbers

shop/views.py
from django.shortcuts import render
from shop.models import Order
from django.db.models import Q

from django.core.validators import validate_email
from django.core.exceptions import ValidationError


def home_view(request):
    """Renders html template when function is called"""
    return render(request, "home.html")


def order_view(request, pizza_type, pizza_size):
    """
    Catch Post Data, validate it and then if valid, create a new Order object in the Database, else render
    template with an error msg
    """
    context = {"pizza_type": pizza_type, "pizza_size": pizza_size}

    if request.POST:
        client_name = request.POST.get("client_name")
        client_email = request.POST.get("client_email")
        client_phone = request.POST.get("client_phone")

        if client_name and client_email and client_phone:
            try:
                validate_email(client_email)
                Order(pizza_type=pizza_type, pizza_size=pizza_size[0], client_name=client_name,
                      client_email=client_email,
                      client_phone=client_phone).save()
                return render(request, "success.html", {"client_name": client_name})
            except ValidationError:
                context["error_msg"] = "Please enter a valid Email!"
        else:
            context["error_msg"] = "Plese fill all Fields!"

    return render(request, "order.html", context)


def order_list_view(request):
    """
    Catch Post Data,then create a set of filtered Order objects according to the given Filters, render List Template
    """
    context = {"orders": Order.objects.all()}

    if request.POST:
        client_name = request.POST.get("client_name")
        client_email = request.POST.get("client_email")

        if client_name and not client_email:
            context = {"orders": Order.objects.filter(client_name__contains=client_name)}
        elif not client_name and client_email:
            context = {"orders": Order.objects.filter(client_email__contains=client_email)}
        elif client_name and client_email:
            context = {"orders": Order.objects.filter(
                Q(client_name__contains=client_name) & Q(client_email__contains=client_email))}
        else:
            context = {"orders": Order.objects.all()}

    return render(request, "orderList.html", context)


def success_view(request):
    """Render success template, usually after an successful order"""
    return render(request, "success.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TwoTicketsPizza</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/logo.jpg' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/4.4_dist_css_bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

<div class="header">
    {% block header %}
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <ul class="navbar-nav mr-auto">
                <li id="overview-nav-item" class="nav-item">
                    <a id="home-nav-item" class="navbar-brand" href="/">
                        <img class="rounded-circle" src="{% static 'img/logo.jpg' %}" width="50" height="50" alt=""> TwoTicketsPizza
                    </a>
                </li>
            </ul>
        </nav>
    {% endblock header %}
</div>

<div class="main" style="min-height: 73vh">
    {% block content %}

    {% endblock content %}
</div>


<div class="footer">
    {% block footer %}
        <footer class="page-footer bg-dark text-light" style="margin: auto">
            <div class="footerimg pt-3">
                <img src="{% static "img/logo.jpg" %}" alt="footer_logo" class="rounded-circle mx-auto d-block"
                     width="100" height="100">
            </div>
            <div class="footer-copyright text-center py-4">© 2021 Copyright: TwoTicketsPizza</div>
        </footer>
    {% endblock footer %}
</div>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<script src="{% static 'js/order_link.js' %}"></script>

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% load static %}
{% block content %}
    <div class="text-center container-fluid">
        <h3 class="mt-4 text-dark">TwoTickets Pizza</h3>
        <hr>

        <div class="card-group">

            <div class="card mr-3" style="width: 18rem;">
                <img class="card-img-top" src="{% static 'img/pizza_salami.jpg' %}" alt="Pizza Salami">
                <div class="card-body">
                    <h5 class="card-title">Pizza Salami 6,99€</h5>
                    <select class="form-control mb-3 pizza_size_select" id="pizza_size_salami" name="pizza_size">
                        <option value="S">Small</option>
                        <option value="M">Medium</option>
                        <option value="L">Large</option>
                    </select>
                    <a class="btn btn-primary order_link" href="/order/Salami/">Order</a>
                </div>
            </div>


            <div class="card mr-3" style="width: 18rem;">
                <img class="card-img-top" src="{% static 'img/pizza_margherita.jpg' %}" alt="Pizza Magherita">
                <div class="card-body">
                    <h5 class="card-title">Pizza Magherita 5,99€</h5>
                    <select class="form-control mb-3 pizza_size_select" id="pizza_size_magherita" name="pizza_size">
                        <option value="M">Medium</option>
                        <option value="L">Large</option>
                    </select>
                    <a class="btn btn-primary order_link" href="/order/Magherita/">Order</a>
                </div>
            </div>


            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{% static 'img/pizza_diavolo.jpg' %}" alt="Pizza Devolo">
                <div class="card-body">
                    <h5 class="card-title">Pizza Diavolo 7,99€</h5>
                    <select class="form-control mb-3 pizza_size_select" id="pizza_size_diavolo" name="pizza_size">
                        <option value="S">Small</option>
                        <option value="M">Medium</option>
                        <option value="L">Large</option>
                    </select>
                    <a class="btn btn-primary order_link" href="/order/Diavolo/">Order</a>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

templates/order.html
{% extends "base.html" %}

{% load static %}
{% block content %}
    <div class="text-center container-fluid">
        <h3 class="mt-4 text-dark">Your choice: One pizza {{ pizza_type }} {{ pizza_size }}</h3>
        <hr>

        <div class="w-50" style="margin-left: 25%">
            <h4>Please fill every field:</h4>
            <form method="POST">
                {% csrf_token %}

                <div class="form-group">
                    <label for="client_name">Name</label>
                    <input type="text" placeholder="Name" class="form-control" id="client_name"
                           name="client_name" maxlength="75">
                </div>
                <div class="form-group">
                    <label for="client_email">Email</label>
                    <input type="text" placeholder="Email" class="form-control" id="client_email"
                           name="client_email" maxlength="255">
                </div>
                <div class="form-group">
                    <label for="client_phone">Phone Number</label>
                    <input type="text" placeholder="Phone Number" class="form-control" id="client_phone"
                           name="client_phone" maxlength="15">
                </div>


                <input type="hidden" name="pizza_type" value="salami">
                <input type="hidden" name="pizza_type" value="salami">
                <button class="btn btn-primary mb-3" type="submit">Order Now!</button>
            </form>

            {% if error_msg %}
                <div class="alert alert-primary mb-3" role="alert" style="margin-top: 15px">
                    {{ error_msg }}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/orderList.html
{% extends "base.html" %}

{% load static %}
{% block content %}
    <div class="text-center container-fluid">
        <h3 class="mt-4 text-dark">All Orders:</h3>
        <hr>

        <div class="row">
            <div class="col-3">
                <form method="POST">
                    {% csrf_token %}
                    <div class="card text-center">
                        <div class="card-header">
                            <h5 class="card-title">Filter</h5>
                        </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label for="client_name">Name</label>
                                <input type="text" placeholder="Name" class="form-control" id="client_name"
                                       name="client_name">
                            </div>
                            <div class="form-group">
                                <label for="client_email">Email</label>
                                <input type="text" placeholder="Email" class="form-control" id="client_email"
                                       name="client_email">
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Filtern</button>
                        </div>
                    </div>
                </form>

            </div>

            <div class="col">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Client Name</th>
                        <th scope="col">Client Email</th>
                        <th scope="col">Pizza Type</th>
                        <th scope="col">Pizza Size</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.client_name }}</td>
                            <td>{{ order.client_email }}</td>
                            <td>{{ order.pizza_type }}</td>
                            <td>{{ order.get_pizza_size_display }}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>

    </div>
{% endblock %}

templates/success.html
{% extends "base.html" %}

{% load static %}
{% block content %}
    <div class="text-center container-fluid" style="margin-top: 20%">
        <h3 class="mt-4 text-dark">Thank you {{ client_name }}, you succsessfully submitted your order!</h3>
        <hr>
        <h4 class="mt-4 text-dark">Your pizza should arrive within the next 15 minutes!:</h4>
        <a class="btn btn-primary mt-1" href="/">Back to Homepage</a>
    </div>
{% endblock %}